"""Add latitude and longitude to injuries

Revision ID: 8d062ddb53a8
Revises: 8e4dac54aca0
Create Date: 2025-02-24 23:02:59.679658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d062ddb53a8'
down_revision: Union[str, None] = '8e4dac54aca0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('injuries', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('injuries', sa.Column('longitude', sa.Float(), nullable=True))
    op.drop_column('injuries', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('injuries', sa.Column('location', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('injuries', 'longitude')
    op.drop_column('injuries', 'latitude')
    # ### end Alembic commands ###
